#!/bin/sh
V=VERSION

## bm, bibliography manager for LaTeX
## Copyright (C) 2019 Cem Keylan <cem@ckyln.com>

##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <https://www.gnu.org/licenses/>.

error() { printf "Error: $1\\n" >&2 ; exit 1;}
msgexit() { printf "$1\\n" ; exit;}

usage() {
	exitcode=$1
	[ -z $1 ] && exitcode="0"
	cat <<EOF
Usage: ${0##*/} <option> [parameter]

  Options:
    
    search  - Search crossref for bibliographic information
    getbib  - Get bibliographic information from pdf or doi and add to bibliography file
    view    - View your bibliography with \$PAGER
    edit    - Edit your bibliography with \$EDITOR
    entry   - Create a bibliography entry with \$EDITOR

    version - Prints version and exits
    help    - Print this help prompt

  Note:
    You must have exported a \$BIB variable where BIB is your bibliography file

EOF
exit $exitcode
}

checkbib() {
	[ -z "$BIB" ] && cat <<EOF && exit
${0##*/}: You don't have a \$BIB variable configured.
To add a \$BIB variable add

  export BIB=/path/to/bib/file.bib

to your shell rc or your profile file
EOF
}


getbib() {
	[ -z "$1" ] && printf "Usage: ${0##*/} getbib <pdf filename or DOI> [optional: explanation]\\n\\n" && exit
	if [ -f "$1" ]; then
		doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
		doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*" -m 1) ||
		exit 1
	else
		doi="$1"
	fi
	err="Resource not found."
	get="$(curl -A "$agent" -s "https://api.crossref.org/works/$doi/transform/application/x-bibtex" -w "\\n")"
	[ "$get" = "$err" ] && error "$err"
	[ -n "$2" ] && printf "// $2\n" >> "$BIB"
	printf "$get\n\n" >> "$BIB"
}


search() {
	[ -z "$1" ] && printf "Usage: ${0##*/} search <search query>\\n\\n" && exit
	jq --version >/dev/null 2>&1 || error "You must install jq for search functionality"
	QUERY="$(echo $1 | sed 's/ /%20/g')"
	mkdir -p /tmp/bm/
	tmpfile=$(mktemp /tmp/bm/search-XXXXXXXX)
	curl -A "$agent" -s https://api.crossref.org/works\?query\="$QUERY" | jq ".message.items[] | select(.author | length >=1) | select(.title | length >=1) | select(.DOI | length >=1) | [.DOI, .author[].given, .author[].family, .title[]] | @csv" > $tmpfile
	while IFS=, read -r doi authorfirst authorlast title; do
		printf "DOI: $doi\nTitle: $title\nFirst Name: $authorfirst\nLast Name: $authorlast\n\n"
	done <$tmpfile
}

entry() {
	[ "$1" = "help" ] && printf "Usage: ${0##*/} entry \"placeholder\"\\n\\n" && exit
	[ -n "$1" ] && ph="$1"
	tmpfile="$(mktemp)"
	cat >$tmpfile <<EOF
// vi:syntax=bib
// Entry in bibtex format
// Change @article to the format you are citing 
// (e.g. @book, @misc)
//
// You can change name_year to your liking, it 
// is there for reference
//
// Lines here will not be added to your bib file
// Remove this line to cancel entry
@article{$ph,
	doi = {$ph},
	url = {$ph},
	year = $ph,
	month = {$ph},
	publisher = {{$ph}},
	volume = {$ph},
	number = {$ph},
	pages = {$ph},
	author = {$ph},
	title = {$ph},
	journal = {$ph}
}

EOF
	${EDITOR-nano} $tmpfile
	grep "Remove this line to cancel entry" $tmpfile >/dev/null 2>&1 || msgexit "Entry canceled"
	rmline="$(grep -nr "Remove this line to cancel entry" $tmpfile | cut -d : -f 1)"
	full="$(cat $tmpfile | wc -l)"
	rmdone="$(expr $full - $rmline)"
	tail -n $rmdone $tmpfile >> $BIB

}


getversion() {
	printf "${0##*/}-$V\n" && exit
}

[ -z "$1" ] && usage 
checkbib
agent="bm/$V (https://git.ckyln.com/bm; mailto: cem@ckyln.com)"
case $1 in
	getbib) getbib "$2" "$3" ;;
	search) search "$2" ;;
	edit) "${EDITOR-nano}" "$BIB" ;;
	view) "${PAGER-less}" "$BIB" ;;
	version) getversion ;;
	entry) entry "$2" ;;
	help) usage;;
	*) printf "${0##*/} -- Unknown option: $1\n\n"; usage 1 ;;
esac
